services:
  - type: web
    name: juice-shop
    runtime: docker
    dockerfilePath: ./juiceshop/Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /

  - type: web
    name: sentinel-shield-proxy
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /healthz
    envVars:
      - key: TARGET_URL
        fromService:
          name: juice-shop
          type: web
      - key: DETECTION_MODE
        value: block
